import tensorflow as tf

class GlobalVariables:
    ACTION_SPACE = 2
    EXPLORE_PROBABILITY = 0.05
    ARRAY_LENGTH = 9
    CENTER_LENGTH = 1
    MAP_SIZE = (2*(ARRAY_LENGTH + CENTER_LENGTH), 2*(ARRAY_LENGTH + CENTER_LENGTH))
    STATE_SPACE = (MAP_SIZE[0], MAP_SIZE[1], 1)
    LENGTH_CELL = 5
    BATCH_SIZE = 64
    GAMMA = 0.95
    EPOCHS = 50
    SAMPLE_SIZE = 256
    INTERVAL = 300
    MEMORY_SIZE = 2048

    step = 0